import 'package:flutter/material.dart';
import 'package:flutter_application_1/enums/Province.dart';

class ProvinceCards {
  AssetImage image;
  String info;
  String tipsTitle;
  String tips;

  ProvinceCards({required this.image, required this.info, required this.tipsTitle, required this.tips});
}

Map<Province, List<ProvinceCards>> provinceCards = {
  Province.Abra: [  
    ProvinceCards(image: const AssetImage('assets/coping_game/abra/abra_lalabayan.png'), info: 'Among the Tingguian, and their neighboring Ilocano, skeining was done using a wooden contraption called lalabayan. The size of the lalabayan enables the simultaneous skeining of multiple sets of yarn', tipsTitle: "Get some exercise", tips: 'Taking care of your physical health can also improve your mental health. Light jogging for a couple of minutes can go a long way.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/abra/abra_tabungaw_hats.png'), info: 'Made by Teofilo Garcis, a National Living Treasure Awardee from Abra who specializes in making these traditional hats that are made from gourds (upo)', tipsTitle: "Acknowledge your loneliness", tips: "The first step to change is always acknowledgement. Having a better understanding of why and how you're lonely can make the process of feeling better easier."),      
    ProvinceCards(image: const AssetImage('assets/coping_game/abra/abra_suyod.png'), info: 'This reed was traditionally used in pedal frame looms. The material is made of bamboo but modern versions of this object has now been using metal versions', tipsTitle: "Improve your sleeping habits", tips: "Getting the right amount of sleep works wonders on how our brains function. It prevents the build up of toxins in the brain which can result in an increased risk of depression."),
    ProvinceCards(image: const AssetImage('assets/coping_game/abra/abra_barkilya.png'), info: 'A barkilya or a "boat shuttle" is a device used to hold the weft yarns, wound a tagintor, across the waro of a pedal frame loom', tipsTitle: "Set limits on time on news social media", tips: "Witnessing negative news can stir more negativity in your head. Better spend your time in relaxing and uplifting activities."),
    ProvinceCards(image: const AssetImage('assets/coping_game/abra/abra_atsuete.png'), info: 'Also known as anatto is a plant that is most used as a condiment. It provides a natural food coloring and is also a source of orange dye for textiles and is also a source of red dyes once its fruit or seeds are crushed', tipsTitle: "Make Time for Self-Care", tips: 'Taking a hot bath sometimes can make you feel refreshed and valued.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/abra/abra_talisay.png'), info: 'Internationally know as the Indian Almond but locally it is called Talisay which is a large tropical tree. Aside from its seeds being edible, it is also a asource of yellow dye. Among the Tingguian tribe, this dye is used to color the threads of their woven blankets.', tipsTitle: "Explore the great outdoors", tips: "Spending some time outdoors lessens the symptoms of depression. Indulging yourself in a green environment can also improve your mood and self-esteem."),
    ProvinceCards(image: const AssetImage('assets/coping_game/abra/abra_kalaleng.png'), info: 'The Kalaleng or also known as the bamboo nose flute is an instrument played where one nostril of the player is plugged and the air is blown from the other end of the flute. Notes are made by the fingers coveing the holes like any other flute. This instrument is most used by men.', tipsTitle: "Do things that you love", tips: "Expressing yourself through something you love doing can make you feel better. It makes you more upbeat and energetic as you do fun-filled activities."),
    ProvinceCards(image: const AssetImage('assets/coping_game/abra/abra_bangued_cathedral.png'), info: 'This church was built in the 19th century originally by the Augustinians but it was greatly damaged during World War II when American warplanes bombed its location. The original altar was destroyed but its tower and walls stood strong. The Secular took over the church and rebuilt it right after the war ended.', tipsTitle: "Eat healthy", tips: "The things we eat can have a direct impact on what we feel or our moods. Here's a tip: foods rich in omega-3 fatty acids can boost your mood."),
  ],
  
  Province.Apayao: [
    ProvinceCards(image: const AssetImage('assets/coping_game/apayao/apayao_sipattal.png'), info: "These are tribal accesories made and worn by the Isneg People. It is considered as one of the most important accessory for both mena women. This object is made of four butterfly shaped mother of pearl piece that are known locaaly as 'bissin'", tipsTitle: "Lifestyle changes", tips: "Making sure you get regular sleep, eat a healthy diet, and exercise regularly can help a lot. Some people benefit from reducing or eliminating the use of caffeine, alcohol, or drugs."),
    ProvinceCards(image: const AssetImage('assets/coping_game/apayao/apayao_aliwa.png'), info: 'It is a axe mostly used by the Isneg people for agriculture specifically when clearing the land in preparation for the planting season', tipsTitle: 'Therapy', tips: 'can be a great way to change behaviors, gain confidence, learn new skills, and talk with someone openly and honestly.'),      
    ProvinceCards(image: const AssetImage('assets/coping_game/apayao/apayao_isnag_abag.png'), info: 'The Isnag tribe from Apayao buy their textiles from their neigbors, the Ilokanos. This piece of cloth is a stylized version of the abag, which is a loincloth worn by Isnag men. The textile was made with a plain weave but is made unique by the addition of different embroidery motifs (rammat) and applique (pontas)', tipsTitle: 'Medication', tips: 'There are many different mental health medications, to help with a variety of symptoms. Medications affect everyone differently, so not every medication will work well for you, and many of them will have side-effects.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/apayao/apayao_mataguisi_church_ruins.png'), info: 'A structure that stands at approximately 6 meters high are the remains of this Spanish church. It demonstrates the ancient designs and accessories during its time. The old Spanish church is a historical landmark remaining in the province which shows the influence of the Spaniards in the past centuries to the historical and cultural fabric of Apayao.', tipsTitle: 'Support', tips: "It's important to find support from others. This can come through family, friends, professionals, or support groups."),
    ProvinceCards(image: const AssetImage('assets/coping_game/apayao/apayao_pottery1.png'), info: 'Pots made from Clay that are often used for culinary purposes. Some pots are now modernized and mixed with bamboo and metal materials. These pots were made for cooking food over charcoal. We made two variations of the pottery made in Apayao', tipsTitle: 'Get feedback from people you trust', tips: "When you're at your lowest point, you'll probably need support and encouragement more than anything."),
    ProvinceCards(image: const AssetImage('assets/coping_game/apayao/apayao_pottery2.png'), info: 'Pots made from Clay that are often used for culinary purposes. Some pots are now modernized and mixed with bamboo and metal materials. These pots were made for cooking food over charcoal. We made two variations of the pottery made in Apayao', tipsTitle: 'Identify your coping skills', tips: 'Try not to label your coping skills as “good” or “bad”. Instead, think about how well they work—short-term, and long-term.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/apayao/apayao_sinibalu.png'), info: 'This is a method of cooking rice in a "buho" or bamboo tubes as practiced by the Isneg people', tipsTitle: 'Track your moods', tips: "Every day, or even multiple times a day, just write down how you're feeling."),
    ProvinceCards(image: const AssetImage('assets/coping_game/apayao/apayao_pas-ing.png'), info: 'This instrument is a two stringed bamboo with a hole in the middle. This instrument is made only from a single bamboo section that is around 3 to four inches in diameter with nodes on each end. The strings are made of the raised narrow strips of the outer skin of the bamboo. This instrument is played by plucking', tipsTitle: 'Pay attention to your thinking', tips: 'Your thoughts influence your feelings, which influence your behaviors. Be on the lookout for negative self-talk and irrational beliefs.'),
  ],

  Province.Benguet: [
    ProvinceCards(image: const AssetImage('assets/coping_game/benguet/benguet_bark_beater.png'), info: 'This device was used to soften the stripped tree bark that is commonly used in cloth making. The basic features of a bark beater are the ridges across its body.', tipsTitle: 'Try not to beat yourself up', tips: 'Beating yourself up is like flailing in the water when someone is trying to rescue you, it will only make things worse.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/benguet/benguet_kiyag.png'), info: 'The kiyag ia used in winnowing rice. During rituals such as those performed during the peshit, it is often used as a tray where materials offerings such as blankets and clothes for the spirits of ancestors are placed.', tipsTitle: "You don't have to hide your feelings", tips: "If you're having really negative thoughts, you can tell yourself a more positive version of the story."),      
    ProvinceCards(image: const AssetImage('assets/coping_game/benguet/benguet_obukay.png'), info: 'People from the Ibaloy tribe make use of the seeds of the obukay and takdian plants (somehwat similar to runo) to make necklaces for both men and women', tipsTitle: 'Make sleep a priority', tips: "Do what you can to make sure you're getting enough sleep to feel rested."),
    ProvinceCards(image: const AssetImage('assets/coping_game/benguet/benguet_lions_head.png'), info: "This man made statue was developed by the Lions of Baguio group back in the 1960's but was only unveiled to the public in 1972. It is a 40-foot structure that was carved of natural limestone by Reynaldo Lopez Nanyac, a Cordilleran artist", tipsTitle: 'Socialize', tips: "Don't let worries isolate you from loved ones or activities."),
    ProvinceCards(image: const AssetImage('assets/coping_game/benguet/benguet_kalasag.png'), info: 'It is a native filipino shiled that was used back in the day by our ancestors during battle. The Kalasag may vary in appearance according to which tribe made them. These shields were usually designed with seashells or with engraved black geometric patterns.', tipsTitle: 'Keep physically active', tips: 'Exercise is a powerful stress reducer. It can improve your mood and help you stay healthy. Start out slowly, and gradually increase the amount and intensity of your activities.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/benguet/benguet_kayabang_basket.png'), info: 'It is a native basket mostly made of bamboo with a rattanfor its base and is originally used by women in Benguet to carry around harvested root crops, vegetables and fruits. The basket is a symbolism of ambudance in the Benguet Culture', tipsTitle: 'Write down your thoughts', tips: 'Writing down what’s making you anxious gets it out of your head and can make it less daunting.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/benguet/benguet_kalsa.png'), info: 'This Ibaloy gong is well known for its use in ritual performances. The Kalsa is part of a gong ensemble that produces a high clear sound', tipsTitle: 'Learn Your Triggers', tips: 'Being aware of what triggers anxiety can help you develop coping mechanisms and prevent symptoms.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/benguet/benguet_solibao.png'), info: 'The Ibaloy use two types of drums, one of which is the solibao which produces a higher note than the other type. Both types of drums are made of cylindrical pieces of wood. The solibao is used together with the gangsa in ritual performances and dances.', tipsTitle: 'Take a Moment to Slow Down', tips: 'Take moments throughout the day to relax and center yourself. Deep breathing or taking part in an activity you enjoy can help break the anxiety cycle.'),
  ],

  Province.Ifugao: [
    ProvinceCards(image: const AssetImage('assets/coping_game/ifugao/ifugao_dinumog.png'), info: 'Multiple pieces of ling-ling-o of the hubong /uvong type are strung together by the Ifugao to form a necklace called dinumog. It is worn by both Ifugao men and women, and serves as a status symbol in more ways than one. Made of gold, each piece of ling-ling-o is in itself a precious item. The symbolic meaning of the pendants, as representations of carabao horns, is a reference to the use of the said animal as sacrifice in the prestige feasts performed by the kadangyan. Wearing a dinumog thus signifies that one has butchered numerous carabaos as ritual offering.', tipsTitle: 'Find ways for relaxation.', tips: 'As Anxiety causes the muscles to tense and our breathing to shorten, relaxation does the opposite. Doing tasks like deep breathing, meditation, and yoga are ways to help our minds and body relax and release all the pent-up tension.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/ifugao/ifugao_hiwang.png'), info: "The hiwang is a personal charm carried by Ifugao men in their butong or hip bags. There are many types of hiwang, among them the hopal (made of twisted wood or roots) and binuha (made of animal bone or teeth). Pieces of hiwang are usually bound in rattan to prevent others from seeing them. This hiwang is of the binuha type. Made of dog teeth and mandible, it is tied to a gong handle with a thin strip of cloth", tipsTitle: 'Talk it out', tips: 'Instead of bottling up all your thoughts and worries, it is always better to find people who can give us constructive feedback in a positive light against the thoughts that entrap us.'),      
    ProvinceCards(image: const AssetImage('assets/coping_game/ifugao/ifugao_punamhan.png'), info: "A ubiquitous object in Ifugao agricultural, divination and healing rituals is the pun’amhan, a carved wooden box used by the mumbaki. Often carved with stylized pigs' heads at both ends, it contains old and new ritual offerings.", tipsTitle: 'Acknowledge your feelings', tips: 'Give yourself the chance and the time to express what you’re feeling. Whatever it is that you are feeling, it is okay to feel that way.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/ifugao/ifugao_tobayan.png'), info: "These are materials that are used to turn fibers into yarn by twisting them. Twisting is usually done using these drope spindles. These objects are also used to produce cotton yarns. The cotton is attached to the pointy end of the spindle and the weight of the disc portion will draw out the fibers. As simple as it seems, the process of twisting requires a great amount of decterity to make sure that all the fibers are continually twisted", tipsTitle: 'Keep a routine', tips: 'Following a healthy routine on a daily basis can help cause a positive impact on your thoughts and feelings.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/ifugao/ifugao_warangan.png'), info: 'This is object was used by the people of Ifugao in the plder methods for skeining. After winding the yarn, it would be subdivided into hanks by knotting them in a set number of threads.', tipsTitle: 'Keep things in perspective', tips: 'A lot of times we think about the “what ifs?”, which leaves us feeling overwhelmed. Shift our mindset to things that we can control or things we can get answers to.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/ifugao/ifugao_bangibang.png'), info: 'It is a set of seven bars made from wood that has its own unique pitch when a player hits them using its stick', tipsTitle: 'Go at your own pace', tips: 'You may feel the need to say yes to everything and go with the flow with everyone but take note that you don’t need to rush. Take control of your life at your own time and as long as it is comfortable for you.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/ifugao/ifugao_balul.png'), info: 'The Bulul is a figure that represents the male rice deity from the Ifugao people. It is an outstanding and highly important expression of the foremost tradition of anthropomorphic sculpture in the northern Philippines.', tipsTitle: 'Do not be afraid to try new things', tips: 'Avoiding things that make us feel anxious may lead us to feel more fearful of them in the future. Try and set small manageable targets to try new things out there.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/ifugao/ifugao_giniling_and_padang.png'), info: "Bracelets (left and right) made of coiled brass wires are used by wealthy Ifugao women. They are usually worn on the right wrist but wealthier women are said to have worn them in both their right and left wrists. Ifugao men wear coiled brass wires called Padang (middle) as leg accessories. The positioning and number of leg accessories worn by a man indicates his rank in traditional Ifugao society. For instance, a kadangyan would usually wear it in both legs, and with matching armlets, while someone of lower middle class background will only wear one on the left leg or both legs but with no matching bracelets", tipsTitle: 'Focus on the now', tips: 'In a fast changing society, we get worried about our future and things from the past a lot. Try to shift your focus instead on the now and live in the moment.'),
  ],

  Province.Kalinga: [
    ProvinceCards(image: const AssetImage('assets/coping_game/kalinga/kalinga_bamboo_container.png'), info: 'These containers made of bamboo are primarily used to store raw cotton before they are processed', tipsTitle: 'Value Yourself', tips: 'Always start with treating yourself with kindness and respect. Make time to do the things that you want or you’ve always wanted to try.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/kalinga/kalinga_bungkaka.png'), info: "The bungkakao or also known as the bamboo buzzer that is played as an ensemble of six. Its sizes vary and slits are cut in its sides that when struck against the hard ulnar part f the hand, it vibrates to create a buzzing sound. During the past, it was believed that the bungkaka was used to drive evil spirits away", tipsTitle: 'Live a healthy lifestyle', tips: 'Taking care of the physical aspect of your body can also significantly improve your mental health. Eating nutritious meals, avoid vices, drinking plety of water, exercise daily and get enough sleep.'),      
    ProvinceCards(image: const AssetImage('assets/coping_game/kalinga/kalinga_ceramics.png'), info: 'The soil originating from the Chico River valley produces clay that makes a good material for potterymaking and thus the people of Kalinga in that area, make a living out of it. While the materials seem plain, the people of Kalinga make distinct decorated pottery by stamping on "tattoo" patterns on to the pots. The sample drawn is a Kalinga Cooking pot in the shape of a horn with a dog handle.', tipsTitle: 'Surround yourself with good people', tips: 'Our environment plays a vital role in our mental helath condition.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/kalinga/kalinga_ceramics2.png'), info: 'The soil originating from the Chico River valley produces clay that makes a good material for potterymaking and thus the people of Kalinga in that area, make a living out of it. While the materials seem plain, the people of Kalinga make distinct decorated pottery by stamping on "tattoo" patterns on to the pots. The sample drawn is a Kalinga Cooking pot in the shape of a horn with a dog handle.', tipsTitle: 'Set realistic goals', tips: 'Decide and set on goals that are realistic and doable. Having little goals that lead to your main goal are also helpful as they give us a sense of accomplishment and self-worth as we progress towards our main goal.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/kalinga/kalinga_earrings.png'), info: 'Made of brass, beads and the mother pearl for the main accent', tipsTitle: 'Don’t hesitate to ask for help', tips: 'Asking for help would be a sign of strength and there is nothing wrong with needing help. People who get appropriate care can recover from mental ilnesses faster and live a rewarding life.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/kalinga/kalinga_baskets_labba.png'), info: 'It is antique basket is used for carrying and storing rice or vegetable and made of rattan and nito vines.', tipsTitle: 'Lifestyle changes', tips: 'Making sure you get regular sleep, eat a healthy diet, and exercise regularly can help a lot. Some people benefit from reducing or eliminating the use of caffeine, alcohol, or drugs.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/kalinga/kalinga_tattoo_patterns.png'), info: 'The famous tribal tattoos made by Apo Whang-od, the last person to be given the title "Mamababatok", are part of the traditions of the Butbut Tribe from Kalinga. The process of tattooing involves the use of thorns, soot, and a small bamboo hammer. Her tattoo patterns all hold a symbolism in their tribe. The patterns used in this app are the traveller, scorpio, snake, and serpent eagle.', tipsTitle: 'Set limits on time on news social media', tips: 'Witnessing negative news can stir more negativity in your head. Better spend your time in relaxing and uplifting activities.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/kalinga/kalinga_tongatong-ing.png'), info: "A bamboo percussion instrument used by the people of Kalinga to communicate with spirits during house blessings. The bamboo is cut into various lengths. When you hit it against soft earth a certain drone reverberates though the instrument's open mouth. When an entire set of Tongatong is played in interloping rhythm and prolonged with the tribal chanting, it could put the audience and the dancers in a trance", tipsTitle: 'Make small changes over time', tips: 'Start with the easy ones first and once you’ve made progress on these, you’ll start feeling more confident.'),
  ],

  Province.MountainProvince: [
    ProvinceCards(image: const AssetImage('assets/coping_game/mountain_province/MtProvince_Gimata.png'), info: 'The gimata is a plaited transport basket used by the Bontok. It is constructed out of two pieces of lavf (grain transport basket) attached to a pole, and is carried by placing it across the shoulders. It is primarily used for transporting rice and other items such as sweet potato. During rituals where large animals such as cows or carabaos are butchered, the gimata is used to transport meat', tipsTitle: 'Learn all you can about yourself', tips: 'Without learning more about yourself, then it would be hard to work on your mental health. Your mental health is who you are, your thoughts, feelings, and actions.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/mountain_province/MtProvince_Kaob.png'), info: "The kaob is a lidded wooden container for storing salted meat. It also takes on a special role during the chono where the cutting of the rattan strings that seal the kaob would signal the start of the feasting.", tipsTitle: 'Track your moods', tips: 'Tracking your positive and negative moods can make you predict your moods, and the less likely you can better cope with them.'),      
    ProvinceCards(image: const AssetImage('assets/coping_game/mountain_province/MtProvince_Lusong.png'), info: 'The lusong is a mortar for pounding rice. It comes in various forms, like this lusong with two mortars. Aside from its daily use, the lusong also takes on a role during the chono where, after the rice is threshed in the lebkan, it is transferred to the lusong for pounding.', tipsTitle: 'Pay attention to your thinking', tips: 'Be on the lookout for irrational beliefs and negative self-talk as these thoughts can influence your feelings and behaviors.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/mountain_province/MtProvince_Belt.png'), info: 'This belt originated from Bontoc and is made of natural fibers, rattan basket shells, and brass tubing. It is usually used as an accessory by women', tipsTitle: 'Identify your coping skills', tips: 'There are alot of different ways to cope with your emotions and you should think about how well they work in the short and long term.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/mountain_province/MtProvince_Sikwan.png'), info: 'It is used to gather or hold yarn to be used for weaving', tipsTitle: 'Get feedback from people you trust', tips: 'When at your lowest point, support and encouragement is important.'),
    ProvinceCards(image: const AssetImage('assets/coping_game/mountain_province/MtProvince_Diwidiwas.png'), info: 'A natibe bamboo wind instrument with one of its ends closed and have no finger holes. The instrument is able to change tone by grouping bamboo pipes with various lengths. To change the tone, one must blow from each pipe', tipsTitle: 'Make small changes over time', tips: "Start with the easy ones first and once you've made progress on these, you'll start feeling more confident."),
    ProvinceCards(image: const AssetImage('assets/coping_game/mountain_province/MtProvince_Buaya.png'), info: 'As rare as the fikum is a necklace made of crocodile teeth worn by elite Bontok men. This necklace, called buaya/foaya, is associated with headhunting rites, ceremonies, and dances. Aside from its use in certain ceremonies, it is also believed that the necklace can serve as a talisman', tipsTitle: 'Keep an open mind', tips: "There are a lot of things that you can try and sometimes the ones that you've most resistant to are things you could really benefit from."),
    ProvinceCards(image: const AssetImage('assets/coping_game/mountain_province/MtProvince_Saong.png'), info: "The saong is a type of necklace that is also used as a head ornament. It is fashioned out of dog teeth or long slender pieces of animal bone interspersed with seed beads. It is usually worn by women.", tipsTitle: 'Talk it out', tips: 'Other people can sometimes see our own thinking traps then ourselves and they can help you get unstuck.'),
  ],
};
